[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "
      default-src 'self'; 
      style-src 'self' 'https://fonts.googleapis.com'; 
      font-src 'self' 'https://fonts.gstatic.com';
    "
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
